// ScriptTranscoder.swift
// word-aligned-state-sync Phase 4 tasks 5.1 / 5.2 / 5.4 — the bidirectional
// codec between `OperationLog` and canonical `.mdocx` Swift source
// (`ooxml-script-transcode` capability; surface per `mdocx-grammar`,
// op wire format per `ooxml-operation-log` — the single normative home).
//
// Projection contract (v0.34 vertical slice):
//
// - DSL form covers the bijective authoring subset: a swift-sourced
//   `appendParagraph(in: nil, payload-with-paraId)` becomes
//   `Paragraph(id: "...", style: .x) { "text" }` inside a synthesized
//   `Section(id: "main")` envelope. The Section wrapper is pure syntax —
//   it emits no operation, so log → script → log stays equivalent.
// - EVERY other op (mutations, word-sourced ops, component envelopes,
//   inline atoms, tables, unknown future ops, …) round-trips via the raw
//   escape line `// @op {canonical JSON fields}` — the forward-compat
//   mechanism the spec mandates for unknown op_types, extended to all
//   DSL-unrepresentable ops so round-trip holds for ARBITRARY logs.
//   Richer DSL-form coverage (setRuns bodies, components, tables) grows
//   in later Phase 4 iterations without breaking this contract.
// - Deterministic formatting: one op ↔ one block/line in log order,
//   4-space indent, no timestamps — adding one op to the log produces
//   exactly one inserted hunk in the exported source (task 5.4).
//
// The importer is a hand-written line-based parser over the CANONICAL
// grammar subset only. It is NOT a Swift compiler: any construct outside
// the canonical form (arbitrary expressions, side effects, unknown
// elements) throws `TranscodeError.unsupportedSyntax(line:column:reason:)`
// with a precise 1-based location.

import Foundation

// MARK: - TranscodeError

public enum TranscodeError: Error, Equatable {
    /// The source contains a construct outside the canonical exporter
    /// grammar. `line`/`column` are 1-based.
    case unsupportedSyntax(line: Int, column: Int, reason: String)
    /// A `// @op` raw line failed to parse back into an Operation.
    case malformedRawOp(line: Int, reason: String)
}

// MARK: - WordStyleMap

/// Bidirectional mapping between OOXML `styleId` strings and `WordStyle`
/// member names (`mdocx-grammar`: "Style references via typed enum").
/// Predefined pairs follow the spec's own example (`Heading1` ↔ `.heading1`);
/// everything else maps verbatim (member name == styleId) when the styleId
/// is a valid Swift identifier that doesn't collide with a predefined member.
enum WordStyleMap {

    static let predefined: [String: String] = {
        var map: [String: String] = [:]   // member -> styleId
        for i in 1...9 { map["heading\(i)"] = "Heading\(i)" }
        map["quote"] = "Quote"
        map["listItem"] = "ListItem"
        map["title"] = "Title"
        map["subtitle"] = "Subtitle"
        return map
    }()

    private static let identifierPattern = try! NSRegularExpression(
        pattern: "^[A-Za-z_][A-Za-z0-9_]*$")

    static func isIdentifier(_ s: String) -> Bool {
        identifierPattern.firstMatch(
            in: s, range: NSRange(s.startIndex..., in: s)) != nil
    }

    /// styleId → `.member` name, or nil when the styleId has no lossless
    /// DSL spelling (caller falls back to the raw `// @op` escape).
    static func member(forStyleId styleId: String) -> String? {
        if let hit = predefined.first(where: { $0.value == styleId }) {
            return hit.key
        }
        guard isIdentifier(styleId) else { return nil }
        // A verbatim member must not collide with a predefined member,
        // or the reverse mapping would rewrite it (e.g. styleId "heading1"
        // verbatim would read back as "Heading1").
        guard predefined[styleId] == nil else { return nil }
        return styleId
    }

    /// `.member` name → verbatim styleId.
    static func styleId(forMember member: String) -> String {
        predefined[member] ?? member
    }
}

// MARK: - ScriptExporter (task 5.1)

public enum ScriptExporter {

    /// Emits canonical `.mdocx` Swift source for the log. Deterministic:
    /// the same log always produces byte-identical output.
    public static func exportSwift(log: OperationLog) -> String {
        var body: [String] = []

        for entry in log.entries {
            if case .appendParagraph(let container, let payload) = entry.op,
               container == nil,
               entry.source == .swift,
               let paraId = payload.paraId, !paraId.isEmpty,
               let block = paragraphBlock(payload: payload, paraId: paraId) {
                body.append(contentsOf: block)
            } else {
                body.append("        " + rawOpLine(entry: entry))
            }
        }

        var out: [String] = []
        out.append("// Generated by ScriptExporter (word-aligned-state-sync Phase 4).")
        out.append("// Canonical .mdocx form — round-trips via ScriptImporter.parse(source:).")
        out.append("import WordDSLSwift")
        out.append("")
        out.append("let document = WordDocument {")
        out.append("    Section(id: \"main\") {")
        out.append(contentsOf: body)
        out.append("    }")
        out.append("}")
        out.append("")
        return out.joined(separator: "\n")
    }

    /// DSL-form paragraph block, or nil when the payload has no lossless
    /// DSL spelling (non-identifier styleId etc.).
    private static func paragraphBlock(payload: ParagraphPayload, paraId: String) -> [String]? {
        var head = "        Paragraph(id: \(quote(paraId))"
        if let styleId = payload.styleId {
            guard let member = WordStyleMap.member(forStyleId: styleId) else { return nil }
            head += ", style: .\(member)"
        }
        head += ") {"
        return [head,
                "            \(quote(payload.text))",
                "        }"]
    }

    /// `// @op {"op_type":...,"source":...,<op fields>}` — canonical raw
    /// escape reusing the JSONL codec's field encoding (single source of
    /// truth for op shapes; op_id/timestamp regenerate on import per the
    /// round-trip contract).
    private static func rawOpLine(entry: LogEntry) -> String {
        let (opType, fields) = JSONLLineCoder.encodeOp(entry.op)
        var parts: [String] = []
        parts.append("\"op_type\":\(quote(opType))")
        parts.append("\"source\":\(quote(entry.source.rawValue))")
        for (key, value) in fields {
            parts.append("\"\(key)\":\(value)")
        }
        return "// @op {\(parts.joined(separator: ","))}"
    }

    static func quote(_ s: String) -> String {
        var escaped = ""
        for ch in s {
            switch ch {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\r": escaped += "\\r"
            case "\t": escaped += "\\t"
            default: escaped.append(ch)
            }
        }
        return "\"\(escaped)\""
    }
}

// MARK: - ScriptImporter (task 5.2)

public enum ScriptImporter {

    private enum Scope { case top, document, section, paragraph }

    private struct ParagraphState {
        var paraId: String
        var styleId: String?
        var textParts: [String] = []
        /// Inline-atom ops collected from the body; flushed AFTER the
        /// paragraph's own appendParagraph op so the atoms' target exists
        /// at replay time.
        var pendingAtoms: [Operation] = []
        var line: Int
    }

    /// Parses canonical `.mdocx` source back into an `OperationLog`.
    /// Accepts exactly the exporter's grammar subset plus hand-written
    /// scripts of the same shape; anything else throws
    /// `TranscodeError.unsupportedSyntax` with a 1-based location.
    public static func parse(source: String) throws -> OperationLog {
        var log = OperationLog()
        var scopeStack: [Scope] = [.top]
        var paragraph: ParagraphState?

        let lines = source.components(separatedBy: "\n")
        for (idx, rawLine) in lines.enumerated() {
            let lineNo = idx + 1
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            let column = (rawLine.count - rawLine.drop(while: { $0 == " " }).count) + 1

            if line.isEmpty { continue }

            // Raw op escape — decode via the JSONL codec (canonical shapes).
            if line.hasPrefix("// @op ") {
                let json = String(line.dropFirst("// @op ".count))
                let entry = try decodeRawOp(json: json, line: lineNo)
                log.append(entry.op, source: entry.source)
                continue
            }
            if line.hasPrefix("//") { continue }               // ordinary comment
            if line == "import WordDSLSwift" { continue }

            switch line {
            case "let document = WordDocument {":
                guard scopeStack.last == .top else {
                    throw TranscodeError.unsupportedSyntax(
                        line: lineNo, column: column, reason: "unexpected WordDocument declaration here")
                }
                scopeStack.append(.document)
                continue
            case "}":
                if paragraph != nil {
                    // close of a Paragraph body
                    let p = paragraph!
                    log.append(.appendParagraph(in: nil, paragraph: ParagraphPayload(
                        text: p.textParts.joined(),
                        styleId: p.styleId,
                        paraId: p.paraId)), source: .swift)
                    for atom in p.pendingAtoms {
                        log.append(atom, source: .swift)
                    }
                    paragraph = nil
                    if scopeStack.last == .paragraph { scopeStack.removeLast() }
                } else if scopeStack.count > 1 {
                    scopeStack.removeLast()
                } else {
                    throw TranscodeError.unsupportedSyntax(
                        line: lineNo, column: column, reason: "unbalanced closing brace")
                }
                continue
            default:
                break
            }

            if let m = match(line, #"^Section\(id: "((?:[^"\\]|\\.)*)"\) \{$"#) {
                guard scopeStack.last == .document else {
                    throw TranscodeError.unsupportedSyntax(
                        line: lineNo, column: column, reason: "Section must be a direct child of WordDocument")
                }
                _ = m   // section id is envelope-only in this slice (no op emitted)
                scopeStack.append(.section)
                continue
            }

            if line.hasPrefix("Paragraph") {
                guard scopeStack.last == .section else {
                    throw TranscodeError.unsupportedSyntax(
                        line: lineNo, column: column, reason: "Paragraph must appear inside a Section")
                }
                if let m = match(line, #"^Paragraph\(id: "((?:[^"\\]|\\.)*)"\) \{$"#) {
                    paragraph = ParagraphState(paraId: unescape(m[0]), styleId: nil, line: lineNo)
                    scopeStack.append(.paragraph)
                    continue
                }
                if let m = match(line, #"^Paragraph\(id: "((?:[^"\\]|\\.)*)", style: \.([A-Za-z_][A-Za-z0-9_]*)\) \{$"#) {
                    paragraph = ParagraphState(
                        paraId: unescape(m[0]),
                        styleId: WordStyleMap.styleId(forMember: m[1]),
                        line: lineNo)
                    scopeStack.append(.paragraph)
                    continue
                }
                if match(line, #"^Paragraph\(id: "(?:[^"\\]|\\.)*", style: "(?:[^"\\]|\\.)*"\) \{$"#) != nil {
                    throw TranscodeError.unsupportedSyntax(
                        line: lineNo, column: column,
                        reason: "raw-string style is rejected — style references require a typed WordStyle value (`style: .heading1`)")
                }
                throw TranscodeError.unsupportedSyntax(
                    line: lineNo, column: column,
                    reason: "Paragraph requires an explicit `id:` argument (mandatory explicit identifiers)")
            }

            if scopeStack.last == .paragraph, paragraph != nil {
                if let m = match(line, #"^"((?:[^"\\]|\\.)*)"$"#) {
                    paragraph!.textParts.append(unescape(m[0]))
                    continue
                }
                // Inline atoms as standalone children (`mdocx-grammar`
                // "Special-character inline atoms"). The paragraph itself is
                // the op target — the reducer synthesizes the wrapping
                // `<w:r>` (rule pinned in `ooxml-operation-log`, §4b).
                // NOTE: the paragraph's appendParagraph op is emitted at the
                // closing brace, AFTER these atom ops — the atoms queue on
                // the pending-atom list and flush after the paragraph op so
                // replay order stays applicable.
                let atomOps: [String: (ElementID) -> Operation] = [
                    "Tab()": { .insertTab(in: $0) },
                    "Break()": { .insertBreak(in: $0) },
                    "NoBreakHyphen()": { .insertNoBreakHyphen(in: $0) },
                ]
                if let makeOp = atomOps[line] {
                    let target = ElementID(rawString: "w14:paraId=\(paragraph!.paraId)")
                    paragraph!.pendingAtoms.append(makeOp(target))
                    continue
                }
                throw TranscodeError.unsupportedSyntax(
                    line: lineNo, column: column,
                    reason: "only String literals and inline atoms (Tab()/Break()/NoBreakHyphen()) are accepted in this paragraph body (canonical subset)")
            }

            throw TranscodeError.unsupportedSyntax(
                line: lineNo, column: column,
                reason: "construct outside the canonical .mdocx transcoder grammar: \(line.prefix(60))")
        }

        guard scopeStack == [.top] else {
            throw TranscodeError.unsupportedSyntax(
                line: lines.count, column: 1, reason: "unterminated block at end of source")
        }
        return log
    }

    // MARK: helpers

    private static func decodeRawOp(json: String, line: Int) throws -> (op: Operation, source: OpSource) {
        guard let data = json.data(using: .utf8),
              let obj = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
              let opType = obj["op_type"] as? String else {
            throw TranscodeError.malformedRawOp(line: line, reason: "raw op line is not a JSON object with op_type")
        }
        let source = OpSource(rawValue: (obj["source"] as? String) ?? "swift") ?? .swift
        do {
            let op = try JSONLLineCoder.decodeOp(opType: opType, fullObject: obj, lineIndex: line)
            return (op, source)
        } catch {
            throw TranscodeError.malformedRawOp(line: line, reason: "cannot decode op '\(opType)': \(error)")
        }
    }

    /// First-match capture groups (regex anchored by caller's pattern).
    private static func match(_ s: String, _ pattern: String) -> [String]? {
        guard let re = try? NSRegularExpression(pattern: pattern) else { return nil }
        let range = NSRange(s.startIndex..., in: s)
        guard let m = re.firstMatch(in: s, range: range) else { return nil }
        var groups: [String] = []
        for i in 1..<m.numberOfRanges {
            guard let r = Range(m.range(at: i), in: s) else { return nil }
            groups.append(String(s[r]))
        }
        return groups
    }

    private static func unescape(_ s: String) -> String {
        var out = ""
        var iterator = s.makeIterator()
        while let ch = iterator.next() {
            if ch == "\\", let next = iterator.next() {
                switch next {
                case "n": out.append("\n")
                case "r": out.append("\r")
                case "t": out.append("\t")
                default: out.append(next)   // \" \\ and anything else literal
                }
            } else {
                out.append(ch)
            }
        }
        return out
    }
}
