// Generated by ScriptExporter (word-aligned-state-sync Phase 4).
// Canonical .mdocx form — round-trips via ScriptImporter.parse(source:).
import WordDSLSwift

let document = WordDocument {
    Section(id: "main") {
        // @op {"op_id":"00000000-0000-4000-8000-000000000001","ts":"1970-01-01T00:00:00Z","op_type":"carryPart","source":"swift","partPath":"[Content_Types].xml","xml":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Types xmlns=\"http:\/\/schemas.openxmlformats.org\/package\/2006\/content-types\">\n    <Default Extension=\"rels\" ContentType=\"application\/vnd.openxmlformats-package.relationships+xml\"\/>\n    <Default Extension=\"xml\" ContentType=\"application\/xml\"\/>\n    <Override PartName=\"\/word\/document.xml\" ContentType=\"application\/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"\/>\n<\/Types>"}
        // @op {"op_id":"00000000-0000-4000-8000-000000000002","ts":"1970-01-01T00:00:00Z","op_type":"carryPart","source":"swift","partPath":"_rels\/.rels","xml":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Relationships xmlns=\"http:\/\/schemas.openxmlformats.org\/package\/2006\/relationships\">\n    <Relationship Id=\"rId1\" Type=\"http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships\/officeDocument\" Target=\"word\/document.xml\"\/>\n<\/Relationships>"}
        // @op {"op_id":"00000000-0000-4000-8000-000000000003","ts":"1970-01-01T00:00:00Z","op_type":"carryPart","source":"swift","partPath":"word\/_rels\/document.xml.rels","xml":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Relationships xmlns=\"http:\/\/schemas.openxmlformats.org\/package\/2006\/relationships\">\n<\/Relationships>"}
        Paragraph(id: "00000001") {
            "Reverse CLI roundtrip content."
        }
        // @op {"op_id":"00000000-0000-4000-8000-000000000005","ts":"1970-01-01T00:00:00Z","op_type":"setSectionProperties","source":"swift","at":null,"section":{}}
    }
}
