// Fixture 15: reverse-cli-roundtrip — EXPECTED REVERSE OUTPUT
//
// This file is the canonical source `macdoc word reverse <docx>` SHALL produce when run against
// the docx generated by sister file `reverse-cli-roundtrip.mdocx.swift`. The runner compares
// the actual reverse output to this file after canonicalization (whitespace normalization +
// parameter order normalization).
//
// Differences from the input source allowed by canonicalization:
//   - Comment headers (input has narrative comments; reverse output has only `// reverse-generated` marker).
//   - Indentation style (reverse output uses 4-space indent uniformly).
//   - Parameter order on Paragraph(id:, style:, ...) follows the spec's parameter ordering even
//     if the input wrote them in a different order.

// reverse-generated from docx
import WordDSLSwift

let document = WordDocument {
    Section(id: "main") {
        Paragraph(id: "p1") {
            "Reverse CLI roundtrip content."
        }
    }
}
